# -*- coding: utf-8 -*-

# python-pastebin
# Wrapper of the pastebin.com API for the Python language.
# Released under the MIT open source license.

# This file contains dicts with constants used by the 
# pastebin.com API.


FORMATS_LIST = [
    "None",
    "4CS",
    "6502 ACME Cross Assembler",
    "6502 Kick Assembler",
    "6502 TASM/64TASS",
    "ABAP",
    "ActionScript",
    "ActionScript 3",
    "Ada",
    "ALGOL 68",
    "Apache Log",
    "AppleScript",
    "APT Sources",
    "ARM",
    "ASM (NASM)",
    "ASP",
    "Asymptote",
    "autoconf",
    "Autohotkey",
    "AutoIt",
    "Avisynth",
    "Awk",
    "BASCOM AVR",
    "Bash",
    "Basic4GL",
    "BibTeX",
    "Blitz Basic",
    "BNF",
    "BOO",
    "BrainFuck",
    "C",
    "C for Macs",
    "C Intermediate Language",
    "C#",
    "C++",
    "C++ (with QT extensions)",
    "C: Loadrunner",
    "CAD DCL",
    "CAD Lisp",
    "CFDG",
    "ChaiScript",
    "Clojure",
    "Clone C",
    "Clone C++",
    "CMake",
    "COBOL",
    "CoffeeScript",
    "ColdFusion",
    "CSS",
    "Cuesheet",
    "D",
    "DCL",
    "DCPU-16",
    "DCS",
    "Delphi",
    "Delphi Prism (Oxygene)",
    "Diff",
    "DIV",
    "DOS",
    "DOT",
    "E",
    "ECMAScript",
    "Eiffel",
    "Email",
    "EPC",
    "Erlang",
    "F#",
    "Falcon",
    "FO Language",
    "Formula One",
    "Fortran",
    "FreeBasic",
    "FreeSWITCH",
    "GAMBAS",
    "Game Maker",
    "GDB",
    "Genero",
    "Genie",
    "GetText",
    "Go",
    "Groovy",
    "GwBasic",
    "Haskell",
    "Haxe",
    "HicEst",
    "HQ9 Plus",
    "HTML",
    "HTML 5",
    "Icon",
    "IDL",
    "INI file",
    "Inno Script",
    "INTERCAL",
    "IO",
    "J",
    "Java",
    "Java 5",
    "JavaScript",
    "jQuery",
    "KiXtart",
    "Latex",
    "LDIF",
    "Liberty BASIC",
    "Linden Scripting",
    "Lisp",
    "LLVM",
    "Loco Basic",
    "Logtalk",
    "LOL Code",
    "Lotus Formulas",
    "Lotus Script",
    "LScript",
    "Lua",
    "M68000 Assembler",
    "MagikSF",
    "Make",
    "MapBasic",
    "MatLab",
    "mIRC",
    "MIX Assembler",
    "Modula 2",
    "Modula 3",
    "Motorola 68000 HiSoft Dev",
    "MPASM",
    "MXML",
    "MySQL",
    "Nagios",
    "newLISP",
    "NullSoft Installer",
    "Oberon 2",
    "Objeck Programming Langua",
    "Objective C",
    "OCalm Brief",
    "OCaml",
    "Octave",
    "OpenBSD PACKET FILTER",
    "OpenGL Shading",
    "Openoffice BASIC",
    "Oracle 11",
    "Oracle 8",
    "Oz",
    "ParaSail",
    "PARI/GP",
    "Pascal",
    "PAWN",
    "PCRE",
    "Per",
    "Perl",
    "Perl 6",
    "PHP",
    "PHP Brief",
    "Pic 16",
    "Pike",
    "Pixel Bender",
    "PL/SQL",
    "PostgreSQL",
    "POV-Ray",
    "Power Shell",
    "PowerBuilder",
    "ProFTPd",
    "Progress",
    "Prolog",
    "Properties",
    "ProvideX",
    "PureBasic",
    "PyCon",
    "Python",
    "Python for S60",
    "q/kdb+",
    "QBasic",
    "R",
    "Rails",
    "REBOL",
    "REG",
    "Rexx",
    "Robots",
    "RPM Spec",
    "Ruby",
    "Ruby Gnuplot",
    "SAS",
    "Scala",
    "Scheme",
    "Scilab",
    "SdlBasic",
    "Smalltalk",
    "Smarty",
    "SPARK",
    "SPARQL",
    "SQL",
    "StoneScript",
    "SystemVerilog",
    "T-SQL",
    "TCL",
    "Tera Term",
    "thinBasic",
    "TypoScript",
    "Unicon",
    "UnrealScript",
    "UPC",
    "Urbi",
    "Vala",
    "VB.NET",
    "Vedit",
    "VeriLog",
    "VHDL",
    "VIM",
    "Visual Pro Log",
    "VisualBasic",
    "VisualFoxPro",
    "WhiteSpace",
    "WHOIS",
    "Winbatch",
    "XBasic",
    "XML",
    "Xorg Config",
    "XPP",
    "YAML",
    "Z80 Assembler",
    "ZXBasic"
]

EXPIRE_LIST = [
    "Never",
    "10 Minutes",
    "1 Hour",
    "1 Day",
    "1 Week",
    "2 Weeks",
    "1 Month"
]

EXPOSURE_LIST = [
    "Public",
    "Unlisted",
    "Private"
]
